server:
  port: ${IDENTITY_PORT:8082}

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASS:example}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/identity?authSource=${MONGO_AUTH_DB:admin}

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  audience: ${JWT_AUDIENCE}
  expiration-hours: ${JWT_EXPIRATION_HOURS:24}
