server:
  port: ${PORT:8080}

services:
  identity:
    baseUrl: ${IDENTITY_BASE_URL:http://localhost:8082}
  applications:
    baseUrl: ${APPLICATIONS_BASE_URL:http://localhost:8083}

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  audience: ${JWT_AUDIENCE}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.csrf: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
