server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:example@localhost:27017/applications?authSource=admin}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

gcs:
  bucket-name: core-application-resumes
  credentials-path: ${GCS_CREDENTIALS_PATH:../gcs-credentials.json}
  project-id: core-fellowship