server:
  port: ${APPLICATIONS_PORT:8083}

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASS:example}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/applications?authSource=${MONGO_AUTH_DB:admin}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

gcs:
  bucket-name: core-application-resumes
  credentials-path: ${GCS_CREDENTIALS_PATH:../gcs-credentials.json}
  project-id: core-fellowship